//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TensionControl.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TensionControl.Languages.language", typeof(language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Onay Şifresi.
        /// </summary>
        public static string adminConfirmation {
            get {
                return ResourceManager.GetString("adminConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici onay şifreniz geçersizdir..
        /// </summary>
        public static string adminConfirmationNotValid {
            get {
                return ResourceManager.GetString("adminConfirmationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici Onayı.
        /// </summary>
        public static string adminConfirmations {
            get {
                return ResourceManager.GetString("adminConfirmations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen kaydı silmek istediğinize emin misiniz?.
        /// </summary>
        public static string areYouSureToDelete {
            get {
                return ResourceManager.GetString("areYouSureToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yapmak istediğinize emin misiniz?.
        /// </summary>
        public static string areYouSureToExit {
            get {
                return ResourceManager.GetString("areYouSureToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yetkili Kişi.
        /// </summary>
        public static string authorized {
            get {
                return ResourceManager.GetString("authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud Rate.
        /// </summary>
        public static string baudRate {
            get {
                return ResourceManager.GetString("baudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanlar boş bırakılamaz..
        /// </summary>
        public static string blanksCannotBeEmpty {
            get {
                return ResourceManager.GetString("blanksCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değişiklikleriniz kaydedildi.
        /// </summary>
        public static string changesSaved {
            get {
                return ResourceManager.GetString("changesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje bitiş tarihlerini kontrol ediniz.
        /// </summary>
        public static string checkDate {
            get {
                return ResourceManager.GetString("checkDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazınızı seçiniz....
        /// </summary>
        public static string chooserChooseSolution {
            get {
                return ResourceManager.GetString("chooserChooseSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirketler.
        /// </summary>
        public static string companies {
            get {
                return ResourceManager.GetString("companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Ekle.
        /// </summary>
        public static string companyAdd {
            get {
                return ResourceManager.GetString("companyAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Grafiği.
        /// </summary>
        public static string companyGraphic {
            get {
                return ResourceManager.GetString("companyGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müşteri Bilgileri.
        /// </summary>
        public static string companyInformation {
            get {
                return ResourceManager.GetString("companyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma bilgisi zaten mevcut.
        /// </summary>
        public static string companyInformationAlreadyExists {
            get {
                return ResourceManager.GetString("companyInformationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma bilgisi silindi.
        /// </summary>
        public static string companyInformationDeleted {
            get {
                return ResourceManager.GetString("companyInformationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma bilgisi kaydedildi.
        /// </summary>
        public static string companyInformationSaved {
            get {
                return ResourceManager.GetString("companyInformationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firma Adı.
        /// </summary>
        public static string companyName {
            get {
                return ResourceManager.GetString("companyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Şirketler.
        /// </summary>
        public static string companyRegistered {
            get {
                return ResourceManager.GetString("companyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmayı Kaydet.
        /// </summary>
        public static string companySave {
            get {
                return ResourceManager.GetString("companySave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket İş Aktiviteleri.
        /// </summary>
        public static string companyWorkActivities {
            get {
                return ResourceManager.GetString("companyWorkActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onayla.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yönetici onay şifresi boş bırakılamaz.
        /// </summary>
        public static string confirmationIsEmpty {
            get {
                return ResourceManager.GetString("confirmationIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı.
        /// </summary>
        public static string connection {
            get {
                return ResourceManager.GetString("connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bağlantı ayarları kaydedildi.
        /// </summary>
        public static string connectionSettingsSaved {
            get {
                return ResourceManager.GetString("connectionSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ulaş.
        /// </summary>
        public static string contact {
            get {
                return ResourceManager.GetString("contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm sorularınız için aşağıdaki iletişim adreslerini kullanarak bizimle iletişime geçebilirsiniz.
        /// </summary>
        public static string contactUsFromAdressess {
            get {
                return ResourceManager.GetString("contactUsFromAdressess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik.
        /// </summary>
        public static string content {
            get {
                return ResourceManager.GetString("content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devam Et.
        /// </summary>
        public static string continueTo {
            get {
                return ResourceManager.GetString("continueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş Emri Oluştur.
        /// </summary>
        public static string createWorkOrder {
            get {
                return ResourceManager.GetString("createWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veri.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarih.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturma Tarihi.
        /// </summary>
        public static string dateCreated {
            get {
                return ResourceManager.GetString("dateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Tarih.
        /// </summary>
        public static string dateDue {
            get {
                return ResourceManager.GetString("dateDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Zaman.
        /// </summary>
        public static string dateDueTime {
            get {
                return ResourceManager.GetString("dateDueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teslim Tarihi.
        /// </summary>
        public static string dateFinished {
            get {
                return ResourceManager.GetString("dateFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje bitiş tarihi geçmiş bir tarih olamaz.
        /// </summary>
        public static string dateIsPast {
            get {
                return ResourceManager.GetString("dateIsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gün.
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz.
        /// </summary>
        public static string device {
            get {
                return ResourceManager.GetString("device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toplam Cihazlar.
        /// </summary>
        public static string deviceAmount {
            get {
                return ResourceManager.GetString("deviceAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz ve Operatör Ayarları.
        /// </summary>
        public static string deviceAndOperatorSettings {
            get {
                return ResourceManager.GetString("deviceAndOperatorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Bilgileri.
        /// </summary>
        public static string deviceData {
            get {
                return ResourceManager.GetString("deviceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz bilgileri güncellendi.
        /// </summary>
        public static string deviceInformationUpdated {
            get {
                return ResourceManager.GetString("deviceInformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Adı.
        /// </summary>
        public static string deviceName {
            get {
                return ResourceManager.GetString("deviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazır Cihazlar.
        /// </summary>
        public static string deviceReady {
            get {
                return ResourceManager.GetString("deviceReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çalışan Cihazlar.
        /// </summary>
        public static string deviceRunning {
            get {
                return ResourceManager.GetString("deviceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihazlar.
        /// </summary>
        public static string devices {
            get {
                return ResourceManager.GetString("devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Ayarları.
        /// </summary>
        public static string deviceSettings {
            get {
                return ResourceManager.GetString("deviceSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz sayısı arttıkça saniye başına alınacak veri miktarı düşecektir. Devam etmek istiyor musunuz?.
        /// </summary>
        public static string deviceWarning {
            get {
                return ResourceManager.GetString("deviceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aynı ada sahip cihaz zaten mevcut.
        /// </summary>
        public static string deviceWithTheSameNameExists {
            get {
                return ResourceManager.GetString("deviceWithTheSameNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çap.
        /// </summary>
        public static string diameter {
            get {
                return ResourceManager.GetString("diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çap 2.
        /// </summary>
        public static string diameter2 {
            get {
                return ResourceManager.GetString("diameter2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çap Fark.
        /// </summary>
        public static string diameterDifference {
            get {
                return ResourceManager.GetString("diameterDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çap Ölçer.
        /// </summary>
        public static string diameterGauge {
            get {
                return ResourceManager.GetString("diameterGauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çap Set.
        /// </summary>
        public static string diameterSet {
            get {
                return ResourceManager.GetString("diameterSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display 3.
        /// </summary>
        public static string display3 {
            get {
                return ResourceManager.GetString("display3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even.
        /// </summary>
        public static string even {
            get {
                return ResourceManager.GetString("even", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        public static string explanation {
            get {
                return ResourceManager.GetString("explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanları doldurunuz.
        /// </summary>
        public static string fillBlanks {
            get {
                return ResourceManager.GetString("fillBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sosyal Medya Hesaplarımızı Takip Edin.
        /// </summary>
        public static string followSocialMedia {
            get {
                return ResourceManager.GetString("followSocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        public static string goBack {
            get {
                return ResourceManager.GetString("goBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik.
        /// </summary>
        public static string graphic {
            get {
                return ResourceManager.GetString("graphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sayfa.
        /// </summary>
        public static string homePage {
            get {
                return ResourceManager.GetString("homePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış kullanıcı adı veya şifre!.
        /// </summary>
        public static string incorrectIdOrPassword {
            get {
                return ResourceManager.GetString("incorrectIdOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Açıklama.
        /// </summary>
        public static string lastExplanation {
            get {
                return ResourceManager.GetString("lastExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metraj.
        /// </summary>
        public static string length {
            get {
                return ResourceManager.GetString("length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinkedIn.
        /// </summary>
        public static string linkedin {
            get {
                return ResourceManager.GetString("linkedin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Adresi.
        /// </summary>
        public static string mailAddress {
            get {
                return ResourceManager.GetString("mailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Seçiniz.
        /// </summary>
        public static string mailChoose {
            get {
                return ResourceManager.GetString("mailChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçerli bir mail adresi giriniz..
        /// </summary>
        public static string mailEmpty {
            get {
                return ResourceManager.GetString("mailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail Listesi.
        /// </summary>
        public static string mailList {
            get {
                return ResourceManager.GetString("mailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgileriniz girmiş olduğunuz mail adresine gönderildi..
        /// </summary>
        public static string mailSent {
            get {
                return ResourceManager.GetString("mailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail gönderildi..
        /// </summary>
        public static string mailSentSuccessful {
            get {
                return ResourceManager.GetString("mailSentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listele.
        /// </summary>
        public static string makeList {
            get {
                return ResourceManager.GetString("makeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En fazla 11 adet veriyi raporlayabilirsiniz.
        /// </summary>
        public static string maxRowToReport {
            get {
                return ResourceManager.GetString("maxRowToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M E N Ü.
        /// </summary>
        public static string menuToggleButton {
            get {
                return ResourceManager.GetString("menuToggleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksi Tolerans.
        /// </summary>
        public static string minusTolerance {
            get {
                return ResourceManager.GetString("minusTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksi Tolerans 2.
        /// </summary>
        public static string minusTolerance2 {
            get {
                return ResourceManager.GetString("minusTolerance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod Bus Yazma.
        /// </summary>
        public static string modBusWrite {
            get {
                return ResourceManager.GetString("modBusWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim Soyisim.
        /// </summary>
        public static string nameSurname {
            get {
                return ResourceManager.GetString("nameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NC.
        /// </summary>
        public static string nc {
            get {
                return ResourceManager.GetString("nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İnternet bağlantısı bulunamadı.
        /// </summary>
        public static string noInternetConnection {
            get {
                return ResourceManager.GetString("noInternetConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port bağlantısı bulunamadı.
        /// </summary>
        public static string noPort {
            get {
                return ResourceManager.GetString("noPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cihaz Sayısı:.
        /// </summary>
        public static string numberOfDevice {
            get {
                return ResourceManager.GetString("numberOfDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opeatör Sayısı:.
        /// </summary>
        public static string numberOfOperator {
            get {
                return ResourceManager.GetString("numberOfOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAMAM.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yalnızca rakam giriniz.
        /// </summary>
        public static string onlyInteger {
            get {
                return ResourceManager.GetString("onlyInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Bilgileri.
        /// </summary>
        public static string operatorInformation {
            get {
                return ResourceManager.GetString("operatorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör bilgisi zaten mevcut.
        /// </summary>
        public static string operatorInformationAlreadyExists {
            get {
                return ResourceManager.GetString("operatorInformationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör bilgisi güncellendi.
        /// </summary>
        public static string operatorInformationUpdated {
            get {
                return ResourceManager.GetString("operatorInformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör.
        /// </summary>
        public static string operators {
            get {
                return ResourceManager.GetString("operators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatörler.
        /// </summary>
        public static string operatorss {
            get {
                return ResourceManager.GetString("operatorss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör Ayarları.
        /// </summary>
        public static string operatorsSettings {
            get {
                return ResourceManager.GetString("operatorsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör İş Aktiviteleri.
        /// </summary>
        public static string operatorsWorkActivities {
            get {
                return ResourceManager.GetString("operatorsWorkActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par-I.
        /// </summary>
        public static string pari {
            get {
                return ResourceManager.GetString("pari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string parity {
            get {
                return ResourceManager.GetString("parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par-P.
        /// </summary>
        public static string parp {
            get {
                return ResourceManager.GetString("parp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Tekrar.
        /// </summary>
        public static string passwordAgain {
            get {
                return ResourceManager.GetString("passwordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz uyuşmamaktadır..
        /// </summary>
        public static string passwordDoesntMatch {
            get {
                return ResourceManager.GetString("passwordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifremi Unuttum.
        /// </summary>
        public static string passwordForgotten {
            get {
                return ResourceManager.GetString("passwordForgotten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreniz 5 haneden küçük veya 16 haneden büyük olamaz.
        /// </summary>
        public static string passwordMinAndMax {
            get {
                return ResourceManager.GetString("passwordMinAndMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Numarası.
        /// </summary>
        public static string phoneNumber {
            get {
                return ResourceManager.GetString("phoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artı Tolerans.
        /// </summary>
        public static string plusTolerance {
            get {
                return ResourceManager.GetString("plusTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artı Tolerans 2.
        /// </summary>
        public static string plusTolerance2 {
            get {
                return ResourceManager.GetString("plusTolerance2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün.
        /// </summary>
        public static string product {
            get {
                return ResourceManager.GetString("product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Ekle.
        /// </summary>
        public static string productAdd {
            get {
                return ResourceManager.GetString("productAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünü Sil.
        /// </summary>
        public static string productDelete {
            get {
                return ResourceManager.GetString("productDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün bilgisi silindi.
        /// </summary>
        public static string productDeleted {
            get {
                return ResourceManager.GetString("productDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün Bilgileri.
        /// </summary>
        public static string productInformation {
            get {
                return ResourceManager.GetString("productInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün bilgisi zaten mevcut.
        /// </summary>
        public static string productInformationAlreadyExists {
            get {
                return ResourceManager.GetString("productInformationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün İsmi.
        /// </summary>
        public static string productName {
            get {
                return ResourceManager.GetString("productName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Ürünler.
        /// </summary>
        public static string productRegistered {
            get {
                return ResourceManager.GetString("productRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürünler.
        /// </summary>
        public static string products {
            get {
                return ResourceManager.GetString("products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ürün bilgisi kaydedildi.
        /// </summary>
        public static string productSaved {
            get {
                return ResourceManager.GetString("productSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje.
        /// </summary>
        public static string project {
            get {
                return ResourceManager.GetString("project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen projeyi iptal et.
        /// </summary>
        public static string projectAbort {
            get {
                return ResourceManager.GetString("projectAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Ekle.
        /// </summary>
        public static string projectAdd {
            get {
                return ResourceManager.GetString("projectAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu proje bir cihaza atanmış bulunmaktadır.
        /// </summary>
        public static string projectAlreadySelected {
            get {
                return ResourceManager.GetString("projectAlreadySelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Adedi.
        /// </summary>
        public static string projectAmount {
            get {
                return ResourceManager.GetString("projectAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen proje bir cihaza atanmış bulunduğundan silinememektedir..
        /// </summary>
        public static string projectCannotBeDeleted {
            get {
                return ResourceManager.GetString("projectCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Seç.
        /// </summary>
        public static string projectChoose {
            get {
                return ResourceManager.GetString("projectChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yeni bir proje kaydı oluşturun.
        /// </summary>
        public static string projectCreateNEwRegister {
            get {
                return ResourceManager.GetString("projectCreateNEwRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Proje Raporu.
        /// </summary>
        public static string projectDailyReport {
            get {
                return ResourceManager.GetString("projectDailyReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeyi Sil.
        /// </summary>
        public static string projectDelete {
            get {
                return ResourceManager.GetString("projectDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje bilgileri silindi.
        /// </summary>
        public static string projectDeleted {
            get {
                return ResourceManager.GetString("projectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinishProject.
        /// </summary>
        public static string projectFinish {
            get {
                return ResourceManager.GetString("projectFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje başarılı bir şekilde bitirildi.
        /// </summary>
        public static string projectFinished {
            get {
                return ResourceManager.GetString("projectFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Bilgileri.
        /// </summary>
        public static string projectInformation {
            get {
                return ResourceManager.GetString("projectInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje Adı.
        /// </summary>
        public static string projectName {
            get {
                return ResourceManager.GetString("projectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje operatör bilgisi güncellendi.
        /// </summary>
        public static string projectOperatorUpdated {
            get {
                return ResourceManager.GetString("projectOperatorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projeler.
        /// </summary>
        public static string projects {
            get {
                return ResourceManager.GetString("projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proje kaydedildi.
        /// </summary>
        public static string projectSaved {
            get {
                return ResourceManager.GetString("projectSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan Projeler.
        /// </summary>
        public static string projectsDone {
            get {
                return ResourceManager.GetString("projectsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük Yapılan Projeler.
        /// </summary>
        public static string projectsDoneDaily {
            get {
                return ResourceManager.GetString("projectsDoneDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Yapılan Projeler.
        /// </summary>
        public static string projectsDoneMonthly {
            get {
                return ResourceManager.GetString("projectsDoneMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık Yapılan Projeler.
        /// </summary>
        public static string projectsDoneWeekly {
            get {
                return ResourceManager.GetString("projectsDoneWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yıllık Yapılan Projeler.
        /// </summary>
        public static string projectsDoneYearly {
            get {
                return ResourceManager.GetString("projectsDoneYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılan Son Projeler.
        /// </summary>
        public static string projectsLast {
            get {
                return ResourceManager.GetString("projectsLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapılacak Projeler.
        /// </summary>
        public static string projectsToDo {
            get {
                return ResourceManager.GetString("projectsToDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beni Hatırla.
        /// </summary>
        public static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlar.
        /// </summary>
        public static string reports {
            get {
                return ResourceManager.GetString("reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oluşturulan Rapor.
        /// </summary>
        public static string reportsCreated {
            get {
                return ResourceManager.GetString("reportsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik Oluştur.
        /// </summary>
        public static string reportsCreateGraphic {
            get {
                return ResourceManager.GetString("reportsCreateGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Oluştur.
        /// </summary>
        public static string reportsCreateReport {
            get {
                return ResourceManager.GetString("reportsCreateReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlanacak Veriler.
        /// </summary>
        public static string reportsData {
            get {
                return ResourceManager.GetString("reportsData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazır Rapor.
        /// </summary>
        public static string reportsReady {
            get {
                return ResourceManager.GetString("reportsReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama kriterlerine uygun sonuç bulunamadı.
        /// </summary>
        public static string searchCannotBeFound {
            get {
                return ResourceManager.GetString("searchCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seç.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az 1 adet arama kriteri seçmelisiniz.
        /// </summary>
        public static string selectAtLeastOneData {
            get {
                return ResourceManager.GetString("selectAtLeastOneData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporlaştırılacak en az bir adet veri seçiniz.
        /// </summary>
        public static string selectDataToReport {
            get {
                return ResourceManager.GetString("selectDataToReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemi gerçekleştirebilmek için satır seçiniz.
        /// </summary>
        public static string selectRowToTakeAction {
            get {
                return ResourceManager.GetString("selectRowToTakeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grafik Ayarları.
        /// </summary>
        public static string settingsGraphicSettings {
            get {
                return ResourceManager.GetString("settingsGraphicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Ayarları.
        /// </summary>
        public static string settingsLanguageSettings {
            get {
                return ResourceManager.GetString("settingsLanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapor Ayarları.
        /// </summary>
        public static string settingsReportSettings {
            get {
                return ResourceManager.GetString("settingsReportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ayarlarınız Kaydedildi....
        /// </summary>
        public static string settingsSaved {
            get {
                return ResourceManager.GetString("settingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Göster.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string signOut {
            get {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string signUp {
            get {
                return ResourceManager.GetString("signUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt işlemi başarılı!.
        /// </summary>
        public static string signUpSucceeded {
            get {
                return ResourceManager.GetString("signUpSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave ID.
        /// </summary>
        public static string slaveID {
            get {
                return ResourceManager.GetString("slaveID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Bit.
        /// </summary>
        public static string stopBit {
            get {
                return ResourceManager.GetString("stopBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konu.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sistem.
        /// </summary>
        public static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gergi Kontrol Cihazı.
        /// </summary>
        public static string tensionControl {
            get {
                return ResourceManager.GetString("tensionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmitter.
        /// </summary>
        public static string transmitter {
            get {
                return ResourceManager.GetString("transmitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter.
        /// </summary>
        public static string twitter {
            get {
                return ResourceManager.GetString("twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unity Mod Bus Studio.
        /// </summary>
        public static string unityModBusStudio {
            get {
                return ResourceManager.GetString("unityModBusStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme işlemi başarılı!.
        /// </summary>
        public static string updateSucceeded {
            get {
                return ResourceManager.GetString("updateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        public static string userName {
            get {
                return ResourceManager.GetString("userName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıtlı Kullanıcı Bulunamadı. Girdiğiniz bilgilerin doğruluğunu kontrol ediniz..
        /// </summary>
        public static string userNotFound {
            get {
                return ResourceManager.GetString("userNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Ayarları.
        /// </summary>
        public static string userSettings {
            get {
                return ResourceManager.GetString("userSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kenar Kontrol Cihazı.
        /// </summary>
        public static string webGuideControl {
            get {
                return ResourceManager.GetString("webGuideControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Sitesi.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoş Geldiniz!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İş emrinin oluşturulabilmesi için cihazlardan en az birine proje ataması yapmış olmanız gerekmektedir.
        /// </summary>
        public static string workOrderNoProject {
            get {
                return ResourceManager.GetString("workOrderNoProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaz.
        /// </summary>
        public static string write {
            get {
                return ResourceManager.GetString("write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazma:.
        /// </summary>
        public static string writing {
            get {
                return ResourceManager.GetString("writing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazma işlemi tamamlandı.
        /// </summary>
        public static string writingSuccessful {
            get {
                return ResourceManager.GetString("writingSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Ekseni.
        /// </summary>
        public static string xAxis {
            get {
                return ResourceManager.GetString("xAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y Ekseni.
        /// </summary>
        public static string yAxis {
            get {
                return ResourceManager.GetString("yAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouTube.
        /// </summary>
        public static string youtube {
            get {
                return ResourceManager.GetString("youtube", resourceCulture);
            }
        }
    }
}
